### ISSUE TITLE
Lisview color

### ISSUE THREAD

**Issue by mkalyon** [mgerlach-klick/cordova-android-listview-alert#1]
Hi, @mgerlach-klick 
Can you add listview element backgroun color, selected element color, and selecting number.
ListViewAlert.show(
	"Infusion Reminder:\nIt's time to take your infusion",
	thelist,
        color1,
        color2,
       selected_number,
	function(selection) {
		return alert("You selected " + selection);
	}
);

color1 = element bacground color, transparent
color2 = selected element color
selected_number = start selected element
Thank you

**Comment by mgerlach-klick** [comment]
Hey, I'm sorry, I haven't touched this in 3 years, nor was I planning to do so again. If you need this functionality, you will have to fork and implement it yourself. The code is pretty straightforward though, so it shouldn't be too hard.

**Comment by mkalyon** [comment]
Thank you @mgerlach-klick 
I will try.
